server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native
  security:
    user:
      name: spring_cloud_user
      password: "{cipher}fa8364998e596cd22955f470f14803cdc83d3a2fe5a2761732a5a0670d5f701c"
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_URI:file:./config-server-repository}

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
encrypt:
  key: ${ENCRYPT_KEY}
